#!/bin/bash


# STEP1 Let's handle what cmd has been invoked by Kublet
case $CNI_COMMAND in
ADD)

;;

DEL)
    
;;

CHECK)
;;

VERSION)

;;

*)
  echo "Not supported: $CNI_COMMAND" 
  exit 1
;;

esac


